amp: true
anomaly_clean: true
batch_size: 128
cuda: true
data_type: molecule_all_h
epochs: 500
freeze_layers: null
freeze_layers_reversed: false
gpu_id: 0
kfold: 4
label_weight:
- 0.3
- 0.7
learning_rate: 0.0001
logger_level: 1
loss_key: weighted_mse
max_epochs: 100
max_norm: 5.0
metrics:
- mse
model_name: unimolv1
num_classes: 2
patience: 20
remove_hs: false
seed: 42
smi_strict: true
smiles_col: SMILES
split: random
split_group_col: scaffold
split_method: 4fold_random
split_seed: 42
target_col_prefix: TARGET
target_cols: TARGET0,TARGET1
target_normalize: auto
task: multilabel_regression
use_amp: true
use_cuda: true
warmup_ratio: 0.03
